// Changelog entries — role-based visibility
// Tags: 'all' (everyone), 'client' (artists/users), 'engineer', 'producer', 'admin'

export type ChangelogTag = 'all' | 'client' | 'engineer' | 'producer' | 'admin';

export interface ChangelogEntry {
  version: string;
  date: string; // YYYY-MM-DD
  title: string;
  description: string;
  tags: ChangelogTag[];
  items: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '2.8.0',
    date: '2026-04-03',
    title: 'UX Improvements & Platform Audit',
    description: 'Major quality-of-life improvements across the entire platform.',
    tags: ['all'],
    items: [
      'Files page now has search, sort by date/name/size, and filter by type',
      'Booking calendar shows green/yellow/red availability before you select a date',
      'Beat store filters are saved in the URL — share filtered views with friends',
      'Session pricing calculator added to your dashboard — estimate costs before booking',
      'New Sweet Dreams favicon icon on browser tabs',
    ],
  },
  {
    version: '2.8.0',
    date: '2026-04-03',
    title: 'Admin KPI Dashboard',
    description: 'New Overview tab with at-a-glance business metrics.',
    tags: ['admin'],
    items: [
      'New Overview tab — first thing you see in admin dashboard',
      'Today/this week/this month revenue, sessions, and beat sales',
      'Pending bookings count, upcoming sessions, outstanding remainders',
      'Recent activity feed — last 5 bookings and 3 beat sales',
    ],
  },
  {
    version: '2.7.0',
    date: '2026-04-03',
    title: 'Platform Security Audit',
    description: 'Comprehensive security and database audit with fixes.',
    tags: ['admin'],
    items: [
      'Fixed FK reference mismatches in booking details and private sales',
      'Fixed SQL injection risks in beat search and purchases queries',
      'Fixed session prep RLS policy — engineers can now properly view client prep',
      'Beat purchases now support nullable fields for private/external sales',
    ],
  },
  {
    version: '2.6.0',
    date: '2026-04-03',
    title: 'Private Beat Sales',
    description: 'Sell beats privately — send buyers a link to review, sign contracts, and pay.',
    tags: ['producer', 'admin'],
    items: [
      'Create private sales from the Beat Manager or Producer dashboard',
      'Three scenarios: unlisted beats, private store beats, recording external sales',
      'Buyers receive email with private link — review, sign license, pay via Stripe or record cash/venmo',
      'Upload custom beat files for sales not in the store',
      'All private sales tracked in accounting with 60/40 split',
    ],
  },
  {
    version: '2.6.0',
    date: '2026-04-03',
    title: 'Beat Purchases & Licenses',
    description: 'Complete purchase flow with license storage and re-downloads.',
    tags: ['client'],
    items: [
      'Login required before purchasing beats — your purchases are linked to your account',
      'New "My Purchases" page — view all beat purchases, re-download files, view licenses',
      'Full license agreement stored with every purchase — access it anytime from your dashboard',
      'Purchase confirmation email with license details',
      'Enhanced license agreements with full Sweet Dreams Music LLC branding',
    ],
  },
  {
    version: '2.6.0',
    date: '2026-04-03',
    title: 'Contracts & Agreements Viewer',
    description: 'Admin can view all contracts, agreements, and license templates.',
    tags: ['admin'],
    items: [
      'New Contracts tab in admin dashboard',
      'View all contract templates — Producer Agreement, MP3 Lease, Trackout, Exclusive',
      'Browse all signed beat licenses, producer agreements, and private sale contracts',
      'Search and filter by name, email, beat title',
      'Expand any contract to see full agreement text',
    ],
  },
  {
    version: '2.5.0',
    date: '2026-04-03',
    title: 'Beat Store Improvements',
    description: 'Dollar pricing, genre dropdowns, auto-generated cover art.',
    tags: ['producer', 'admin'],
    items: [
      'Pricing inputs now accept dollar amounts ($29.99) instead of cents',
      'Genre is a dropdown with 15 curated options — each maps to unique cover art colors',
      'Auto-generated SVG cover art on beat upload — Sweet Dreams branding',
      '"Sweet Dreams" tag automatically added to every beat',
      'Fixed beat upload failure — status constraint and storage bucket corrected',
    ],
  },
  {
    version: '2.5.0',
    date: '2026-04-03',
    title: 'Producer Sale Notifications',
    description: 'Producers get notified when someone buys their beat.',
    tags: ['producer'],
    items: [
      'Email notification when a beat is purchased — includes buyer info and your 60% earnings',
      'Buyers get purchase confirmation email with license details',
    ],
  },
  {
    version: '2.4.0',
    date: '2026-04-02',
    title: 'Half-Built Features Completed',
    description: 'Finished and polished features that were partially built.',
    tags: ['all'],
    items: [
      'Achievements system — 14 milestones with progress bars and XP rewards',
      'Interactive artist roadmap — check off items, earn XP, track progress',
      'Metrics trend charts — sparklines and growth rate indicators for platform stats',
      'Career stage and genre — set in profile editor, displayed on public profile',
      'Welcome email sent automatically on first signup',
    ],
  },
  {
    version: '2.4.0',
    date: '2026-04-02',
    title: 'Session Notes Visibility',
    description: 'Engineers can control which session notes clients see.',
    tags: ['engineer'],
    items: [
      'Eye/EyeOff toggle on each session note — control client visibility',
      'Default: visible to client. Toggle off for internal-only notes',
      'Clients only see notes marked as visible',
    ],
  },
  {
    version: '2.4.0',
    date: '2026-04-02',
    title: 'XP System Expansion',
    description: 'More ways to earn XP with auto-detection and deduplication.',
    tags: ['client'],
    items: [
      'Earn XP for booking sessions, purchasing beats, completing profile',
      'Login streaks — 3-day and 7-day milestones',
      'XP breakdown panel — click level badge to see last 5 XP entries',
      'Auto-detection from Stripe webhook — no manual claiming needed',
    ],
  },
  {
    version: '2.3.0',
    date: '2026-04-02',
    title: 'Payroll & Accounting Overhaul',
    description: 'Complete financial tracking for the business.',
    tags: ['admin'],
    items: [
      'New Payroll tab — per-person earnings across sessions, media, and beats',
      'Business profit breakdown — gross revenue minus payroll plus kept deposits',
      'Media sales split: 15% sales commission, 35% business, 50% worker',
      'Centralized commission constants for all revenue streams',
      'Payout tracking — mark payments as made, track what is still owed',
    ],
  },
  {
    version: '2.3.0',
    date: '2026-04-02',
    title: 'Payment Management Buttons',
    description: 'More ways to record and manage session payments.',
    tags: ['admin', 'engineer'],
    items: [
      'Record Cash — log cash payments with notes',
      'Record Stripe — mark Stripe payments received outside the app',
      'Send Payment Link — create Stripe checkout and email to client',
      'Mark Paid in Full — zero out remainder instantly',
      'Fixed admin notes race condition that was clobbering payment updates',
    ],
  },
  {
    version: '2.2.0',
    date: '2026-04-01',
    title: 'File Downloads & Delivery',
    description: 'Better file management for everyone.',
    tags: ['all'],
    items: [
      'File downloads now force download instead of playing in browser (works on mobile)',
      'Engineers can download files from any artist\'s Client Library',
      'Admins can upload files to any session booking',
      'Public profile toggle — share unreleased music on your profile',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-03-28',
    title: 'Session Prep Flow',
    description: 'Prepare for your sessions before arriving at the studio.',
    tags: ['client'],
    items: [
      'Pre-session prep page — add lyrics, references, notes before your session',
      'Engineers can view your prep to plan the session',
      'Prep reminder included in booking confirmation',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-03-20',
    title: 'Beat Store Launch',
    description: 'Full beat marketplace with licensing, checkout, and producer system.',
    tags: ['all'],
    items: [
      'Browse beats by genre, BPM, producer — with audio preview',
      'Three license tiers: MP3 Lease, Trackout Lease, Exclusive Rights',
      'Save beats to your library for later',
      'Writing pad — write lyrics while listening to beats',
      'Producer applications and approval system',
      'Producer dashboard with earnings tracking',
      'Beat upload with admin review → producer agreement signing flow',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-03-15',
    title: 'Artist Hub',
    description: 'Your personal artist development headquarters.',
    tags: ['client'],
    items: [
      'Project tracker — manage releases through 8 phases (concept to released)',
      'Goal setting with progress tracking',
      'Metrics dashboard — log your platform numbers weekly',
      'Content calendar — plan releases, posts, and shows',
      'Achievements and XP leveling system',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-03-10',
    title: 'Engineer Invite System',
    description: 'Engineers can invite clients directly to book sessions.',
    tags: ['engineer'],
    items: [
      'Create session invites with custom pricing',
      'Send invite link via email — client clicks to book and pay',
      'Same-day pricing automatically applied for invite bookings',
      'Auto-claim: sessions booked via your invite are assigned to you',
      'Pending invites section on engineer dashboard',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-03-05',
    title: 'Media Sales Tracking',
    description: 'Track videography, photography, and content creation revenue.',
    tags: ['engineer', 'admin'],
    items: [
      'Log media sales with type, crew, and client info',
      'Commission tracking: 15% to seller, 50% to worker, 35% to business',
      'Client search — pick existing users or enter manually',
      'Edit and delete media sales entries',
      'Media sales included in accounting and payroll',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-02-20',
    title: 'Public Profiles',
    description: 'Share your artist profile with the world.',
    tags: ['client'],
    items: [
      'Public profile page at sweetdreamsmusic.com/u/your-name',
      'Profile picture, cover photo, bio, and social links',
      'Showcase released and unreleased music',
      'Display your projects and discography',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-02-01',
    title: 'Booking System Upgrades',
    description: 'Smoother booking experience with more options.',
    tags: ['all'],
    items: [
      'Sweet Spot pricing — best rates for 4-hour sessions',
      'Late night and deep night surcharges clearly shown',
      'Same-day booking fee ($10/hr)',
      'Reschedule requests from your dashboard',
      'Booking confirmation and reminder emails',
    ],
  },
  {
    version: '1.0.0',
    date: '2025-12-01',
    title: 'Platform Launch',
    description: 'Sweet Dreams Music recording studio booking platform goes live.',
    tags: ['all'],
    items: [
      'Online session booking with Stripe payments',
      'Studio A and Studio B with 24-hour availability',
      'Engineer profiles and session assignment',
      'Client dashboard with booking history and file downloads',
      'Admin dashboard with booking management',
    ],
  },
];
